
project_id = "pvplhqzzhmqseyzooags"

[functions.radius-auth]
verify_jwt = false

[functions.radius-accounting]
verify_jwt = false

[functions.radius-coa]
verify_jwt = false

[functions.ai-chat-enhanced]
verify_jwt = false

[functions.ai-translation] 
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.ai-mobile-money]
verify_jwt = false

[functions.chat-ai-router]
verify_jwt = false

[functions.chat-message-handler]
verify_jwt = false
