// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvplhqzzhmqseyzooags.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cGxocXp6aG1xc2V5em9vYWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjQ1OTEsImV4cCI6MjA2MjA0MDU5MX0.fuY_iQggPq8BXpaXf1nDjHlBhXF-NxexJICoTRbV4n8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);